### PR TITLE
modify the function inside the controller to return my name

### PR DESCRIPTION
**Pull request by Morzanne**
-I modified the name of the function into 'aurelien'
-I modified what the function have to return

### CODE REVIEW

**Review by petitbx — CHANGES_REQUESTED** [review]
You don't have to update my function but create a new one

**Review by Xgt72 — CHANGES_REQUESTED** [review]
You have to add your function after benoitXavier function.

**Review by Morzanne — COMMENTED** [review]
I finally add my own function and let bx's function live

**Review by petitbx — CHANGES_REQUESTED** [review]
Where is `}` ?

**Review by petitbx — APPROVED** [review]

**Review by ayantot — APPROVED** [review]

**Review by Xgt72 — APPROVED** [review]

**Pull request merged**
