### PR TITLE
Update Gitignore and create first controller and function

### PR DESCRIPTION
**Pull request by petitbx**
- Update gitignore because I worked on PHPStorm
- Create Controller and first function for students

### CODE REVIEW

**Review by celine28240 — APPROVED** [review]

**Review by Brandon28400 — APPROVED** [review]
Good job :)

**Review by LucLev — APPROVED** [review]
That's some good Gitflow

**Review by magmirl — APPROVED** [review]

**Review by Fabien-V — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by ayantot** [comment]
Good !

**Review by ghost — APPROVED** [review]
Incredible, awesome, sweet baby Jesus !

**Review by ghost — APPROVED** [review]
Wonderful !

**Pull request merged**
