### PR TITLE
Create function julien in indexController

### PR DESCRIPTION
**Pull request by Pompidup**
- Create julien function for display my name in indexController

### CODE REVIEW

**Review by Xgt72 — APPROVED** [review]
That's ok.

**Review by petitbx — CHANGES_REQUESTED** [review]
Code is not indent

**Review by petitbx — APPROVED** [review]
Good job !

**Comment by TalRino** [comment]
Good Job !

**Review by yorannelisabeth — APPROVED** [review]
bouya

**Pull request merged**
