### PR TITLE
Quentin Function 

### PR DESCRIPTION
**Pull request by Zarbtinou**
add Quentin function

### CODE REVIEW

**Review by Brandon28400 — COMMENTED** [review]
Same title and description ?

**Review by Tshintuu — APPROVED** [review]
Good! I approve! You did great by fixing the bug, awesome initiative!

**Review by petitbx — CHANGES_REQUESTED** [review]
You don't have to change the function of Julien

**Comment by Zarbtinou** [comment]
I Rename my PR

**Pull request closed without merging**
